require("ron.plugins-setup")
require("ron.core.options")
require("ron.core.keymaps")
require("ron.core.colorscheme")
require("ron.plugins.comment")
require("ron.plugins.nvim-tree")
require("ron.plugins.lualine")
require("ron.plugins.telescope")
require("ron.plugins.nvim-cmp")
require("ron.plugins.lsp.mason")
require("ron.plugins.lsp.lspsaga")
require("ron.plugins.lsp.lspconfig")
require("ron.plugins.lsp.null-ls")
require("ron.plugins.autopairs")
require("ron.plugins.treesitter")
require("ron.plugins.gitsigns")

